-- !Ups

INSERT INTO nationality (name) values ('Afghan');
INSERT INTO nationality (name) values ('Albania');
INSERT INTO nationality (name) values ('Algeria');
INSERT INTO nationality (name) values ('American');
INSERT INTO nationality (name) values ('Andorra');
INSERT INTO nationality (name) values ('Angolan');
INSERT INTO nationality (name) values ('Anguillan');
INSERT INTO nationality (name) values ('Argentine');
INSERT INTO nationality (name) values ('Armenian');
INSERT INTO nationality (name) values ('Australia');
INSERT INTO nationality (name) values ('Austria');
INSERT INTO nationality (name) values ('Azerbaijan');
INSERT INTO nationality (name) values ('Bahamian');
INSERT INTO nationality (name) values ('Bahrain');
INSERT INTO nationality (name) values ('Bangladeshi');
INSERT INTO nationality (name) values ('Barbadian');
INSERT INTO nationality (name) values ('Belarusian');
INSERT INTO nationality (name) values ('Belgium');
INSERT INTO nationality (name) values ('Belizean');
INSERT INTO nationality (name) values ('Beninese');
INSERT INTO nationality (name) values ('Bermudian');
INSERT INTO nationality (name) values ('Bhutanese');
INSERT INTO nationality (name) values ('Bolivia');
INSERT INTO nationality (name) values ('Botswanan');
INSERT INTO nationality (name) values ('Brazil');
INSERT INTO nationality (name) values ('British');
INSERT INTO nationality (name) values ('British Virgin Islander');
INSERT INTO nationality (name) values ('Bruneian');
INSERT INTO nationality (name) values ('Bulgarian');
INSERT INTO nationality (name) values ('Burkinan');
INSERT INTO nationality (name) values ('Burmese');
INSERT INTO nationality (name) values ('Burundian');
INSERT INTO nationality (name) values ('Cambodian');
INSERT INTO nationality (name) values ('Cameroonian');
INSERT INTO nationality (name) values ('Canadian');
INSERT INTO nationality (name) values ('Cape Verdean');
INSERT INTO nationality (name) values ('Cayman Islander');
INSERT INTO nationality (name) values ('Central African');
INSERT INTO nationality (name) values ('Chadian');
INSERT INTO nationality (name) values ('Chilean');
INSERT INTO nationality (name) values ('Chinese');
INSERT INTO nationality (name) values ('Citizen of Antigua and Barbuda');
INSERT INTO nationality (name) values ('Citizen of Bosnia and Herzegovina');
INSERT INTO nationality (name) values ('Citizen of Guinea-Bissau');
INSERT INTO nationality (name) values ('Citizen of Kiribati');
INSERT INTO nationality (name) values ('Citizen of Seychelles');
INSERT INTO nationality (name) values ('Citizen of the Dominican Republic');
INSERT INTO nationality (name) values ('Citizen of Vanuatu');
INSERT INTO nationality (name) values ('Colombian');
INSERT INTO nationality (name) values ('Comoran');
INSERT INTO nationality (name) values ('Congolese (Congo)');
INSERT INTO nationality (name) values ('Congolese (DRC)');
INSERT INTO nationality (name) values ('Cook Islander');
INSERT INTO nationality (name) values ('Costa Rican');
INSERT INTO nationality (name) values ('Croatian');
INSERT INTO nationality (name) values ('Cuban');
INSERT INTO nationality (name) values ('Cymraes');
INSERT INTO nationality (name) values ('Cymro');
INSERT INTO nationality (name) values ('Cypriot');
INSERT INTO nationality (name) values ('Czech');
INSERT INTO nationality (name) values ('Danish');
INSERT INTO nationality (name) values ('Djiboutian');
INSERT INTO nationality (name) values ('Dominican');
INSERT INTO nationality (name) values ('Dutch');
INSERT INTO nationality (name) values ('East Timorese');
INSERT INTO nationality (name) values ('Ecuadorean');
INSERT INTO nationality (name) values ('Egyptian');
INSERT INTO nationality (name) values ('Emirati');
INSERT INTO nationality (name) values ('English');
INSERT INTO nationality (name) values ('Equatorial Guinean');
INSERT INTO nationality (name) values ('Eritrean');
INSERT INTO nationality (name) values ('Estonian');
INSERT INTO nationality (name) values ('Ethiopian');
INSERT INTO nationality (name) values ('Faroese');
INSERT INTO nationality (name) values ('Fijian');
INSERT INTO nationality (name) values ('Filipino');
INSERT INTO nationality (name) values ('Finnish');
INSERT INTO nationality (name) values ('French');
INSERT INTO nationality (name) values ('Gabonese');
INSERT INTO nationality (name) values ('Gambian');
INSERT INTO nationality (name) values ('Georgian');
INSERT INTO nationality (name) values ('German');
INSERT INTO nationality (name) values ('Ghanaian');
INSERT INTO nationality (name) values ('Gibraltarian');
INSERT INTO nationality (name) values ('Greek');
INSERT INTO nationality (name) values ('Greenlandic');
INSERT INTO nationality (name) values ('Grenadian');
INSERT INTO nationality (name) values ('Guamanian');
INSERT INTO nationality (name) values ('Guatemalan');
INSERT INTO nationality (name) values ('Guinean');
INSERT INTO nationality (name) values ('Guyanese');
INSERT INTO nationality (name) values ('Haitian');
INSERT INTO nationality (name) values ('Honduran');
INSERT INTO nationality (name) values ('Hong Konger');
INSERT INTO nationality (name) values ('Hungarian');
INSERT INTO nationality (name) values ('Icelandic');
INSERT INTO nationality (name) values ('Indian');
INSERT INTO nationality (name) values ('Indonesian');
INSERT INTO nationality (name) values ('Iranian');
INSERT INTO nationality (name) values ('Iraqi');
INSERT INTO nationality (name) values ('Irish');
INSERT INTO nationality (name) values ('Israeli');
INSERT INTO nationality (name) values ('Italian');
INSERT INTO nationality (name) values ('Ivorian');
INSERT INTO nationality (name) values ('Jamaican');
INSERT INTO nationality (name) values ('Japanese');
INSERT INTO nationality (name) values ('Jordanian');
INSERT INTO nationality (name) values ('Kazakh');
INSERT INTO nationality (name) values ('Kenyan');
INSERT INTO nationality (name) values ('Kittitian');
INSERT INTO nationality (name) values ('Kosovan');
INSERT INTO nationality (name) values ('Kuwaiti');
INSERT INTO nationality (name) values ('Kyrgyz');
INSERT INTO nationality (name) values ('Lao');
INSERT INTO nationality (name) values ('Latvian');
INSERT INTO nationality (name) values ('Lebanese');
INSERT INTO nationality (name) values ('Liberian');
INSERT INTO nationality (name) values ('Libyan');
INSERT INTO nationality (name) values ('Liechtenstein citizen');
INSERT INTO nationality (name) values ('Lithuanian');
INSERT INTO nationality (name) values ('Luxembourger');
INSERT INTO nationality (name) values ('Macanese');
INSERT INTO nationality (name) values ('Macedonian');
INSERT INTO nationality (name) values ('Malagasy');
INSERT INTO nationality (name) values ('Malawian');
INSERT INTO nationality (name) values ('Malaysian');
INSERT INTO nationality (name) values ('Maldivian');
INSERT INTO nationality (name) values ('Malian');
INSERT INTO nationality (name) values ('Maltese');
INSERT INTO nationality (name) values ('Marshallese');
INSERT INTO nationality (name) values ('Martiniquais');
INSERT INTO nationality (name) values ('Mauritanian');
INSERT INTO nationality (name) values ('Mauritian');
INSERT INTO nationality (name) values ('Mexican');
INSERT INTO nationality (name) values ('Micronesian');
INSERT INTO nationality (name) values ('Moldovan');
INSERT INTO nationality (name) values ('Monegasque');
INSERT INTO nationality (name) values ('Mongolian');
INSERT INTO nationality (name) values ('Montenegrin');
INSERT INTO nationality (name) values ('Montserratian');
INSERT INTO nationality (name) values ('Moroccan');
INSERT INTO nationality (name) values ('Mosotho');
INSERT INTO nationality (name) values ('Mozambican');
INSERT INTO nationality (name) values ('Namibian');
INSERT INTO nationality (name) values ('Nauruan');
INSERT INTO nationality (name) values ('Nepalese');
INSERT INTO nationality (name) values ('New Zealander');
INSERT INTO nationality (name) values ('Nicaraguan');
INSERT INTO nationality (name) values ('Nigerian');
INSERT INTO nationality (name) values ('Nigerien');
INSERT INTO nationality (name) values ('Niuean');
INSERT INTO nationality (name) values ('North Korean');
INSERT INTO nationality (name) values ('Northern Irish');
INSERT INTO nationality (name) values ('Norwegian');
INSERT INTO nationality (name) values ('Omani');
INSERT INTO nationality (name) values ('Pakistani');
INSERT INTO nationality (name) values ('Palauan');
INSERT INTO nationality (name) values ('Palestinian');
INSERT INTO nationality (name) values ('Panamanian');
INSERT INTO nationality (name) values ('Papua New Guinean');
INSERT INTO nationality (name) values ('Paraguayan');
INSERT INTO nationality (name) values ('Peruvian');
INSERT INTO nationality (name) values ('Pitcairn Islander');
INSERT INTO nationality (name) values ('Polish');
INSERT INTO nationality (name) values ('Portuguese');
INSERT INTO nationality (name) values ('Prydeinig');
INSERT INTO nationality (name) values ('Puerto Rican');
INSERT INTO nationality (name) values ('Qatari');
INSERT INTO nationality (name) values ('Romanian');
INSERT INTO nationality (name) values ('Russian');
INSERT INTO nationality (name) values ('Rwandan');
INSERT INTO nationality (name) values ('Salvadorean');
INSERT INTO nationality (name) values ('Sammarinese');
INSERT INTO nationality (name) values ('Samoan');
INSERT INTO nationality (name) values ('Sao Tomean');
INSERT INTO nationality (name) values ('Saudi Arabian');
INSERT INTO nationality (name) values ('Scottish');
INSERT INTO nationality (name) values ('Senegalese');
INSERT INTO nationality (name) values ('Serbian');
INSERT INTO nationality (name) values ('Sierra Leonean');
INSERT INTO nationality (name) values ('Singaporean');
INSERT INTO nationality (name) values ('Slovak');
INSERT INTO nationality (name) values ('Slovenian');
INSERT INTO nationality (name) values ('Solomon Islander');
INSERT INTO nationality (name) values ('Somali');
INSERT INTO nationality (name) values ('South African');
INSERT INTO nationality (name) values ('South Korean');
INSERT INTO nationality (name) values ('South Sudanese');
INSERT INTO nationality (name) values ('Spanish');
INSERT INTO nationality (name) values ('Sri Lankan');
INSERT INTO nationality (name) values ('St Helenian');
INSERT INTO nationality (name) values ('St Lucian');
INSERT INTO nationality (name) values ('Stateless');
INSERT INTO nationality (name) values ('Sudanese');
INSERT INTO nationality (name) values ('Surinamese');
INSERT INTO nationality (name) values ('Swazi');
INSERT INTO nationality (name) values ('Swedish');
INSERT INTO nationality (name) values ('Swiss');
INSERT INTO nationality (name) values ('Syrian');
INSERT INTO nationality (name) values ('Taiwanese');
INSERT INTO nationality (name) values ('Tajik');
INSERT INTO nationality (name) values ('Tanzanian');
INSERT INTO nationality (name) values ('Thai');
INSERT INTO nationality (name) values ('Togolese');
INSERT INTO nationality (name) values ('Tongan');
INSERT INTO nationality (name) values ('Trinidadian');
INSERT INTO nationality (name) values ('Tristanian');
INSERT INTO nationality (name) values ('Tunisian');
INSERT INTO nationality (name) values ('Turkish');
INSERT INTO nationality (name) values ('Turkmen');
INSERT INTO nationality (name) values ('Turks and Caicos Islander');
INSERT INTO nationality (name) values ('Tuvaluan');
INSERT INTO nationality (name) values ('Ugandan');
INSERT INTO nationality (name) values ('Ukrainian');
INSERT INTO nationality (name) values ('Uruguayan');
INSERT INTO nationality (name) values ('Uzbek');
INSERT INTO nationality (name) values ('Vatican citizen');
INSERT INTO nationality (name) values ('Venezuelan');
INSERT INTO nationality (name) values ('Vietnamese');
INSERT INTO nationality (name) values ('Vincentian');
INSERT INTO nationality (name) values ('Wallisian');
INSERT INTO nationality (name) values ('Welsh');
INSERT INTO nationality (name) values ('Yemeni');
INSERT INTO nationality (name) values ('Zambian');
INSERT INTO nationality (name) values ('Zimbabwean');

INSERT INTO traveller_type (name) values ('Thrill-Seeker');
INSERT INTO traveller_type (name) values ('Functional/Business Traveller');
INSERT INTO traveller_type (name) values ('Holiday Maker');
INSERT INTO traveller_type (name) values ('Backpacker');
INSERT INTO traveller_type (name) values ('Groupies');
INSERT INTO traveller_type (name) values ('Frequent Weekender');
INSERT INTO traveller_type (name) values ('Gap Year');


INSERT INTO user (first_name, middle_name, last_name, date_of_birth, gender, email, password, timestamp, account_type) VALUES ('Global', '', 'Admin', 0, 'Male', 'admin@admin.com', '0b92abaa6ba4238079530ab9b9c23e6fa9585324ef5039f953816b3937e6fabad990a33c8348dba7a134ae4169cba4e1481538c6ba9b8fe5414de4d1393c862e', 1529196155, 2);
INSERT INTO album (name, user_id, is_permanent, deleted) VALUES ('All', 1, true, false);

-- !Downs

DELETE FROM nationality;
DELETE FROM traveller_type;

DELETE FROM User WHERE account_type = 2;