tag_checker:
  stage: build
  script:
    - python tag_checker.py $CI_COMMIT_TAG
  only:
    - tags

junit:
  stage: test
  script:
    - cd ./backend
    - sbt test

recent-artifacts:
  stage: deploy
  script:
    - cd ./backend
    - sbt dist
    
    # Kill existing process (if any)
    - echo $PWD
    
    - kill $(cat target/universal/team300-travelea-1.0.0-SNAPSHOT/RUNNING_PID)
    
    # Deploy to server http://csse-s302g3.canterbury.ac.nz:8443/
    - cd target/universal
    - unzip team300-travelea-1.0.0-SNAPSHOT.zip
    - rm team300-travelea-1.0.0-SNAPSHOT.zip
    - cd team300-travelea-1.0.0-SNAPSHOT/bin
    - ./team300-travelea -Dplay.http.secret.key=QCYtAnfkaZiwrNwnxIlR6CTfG3gf90Latabg5241ABR5W1uDFNIk1 -Dplay.evolutions.db.default.autoApply=true -Dhttp.port=8443
    - disown -h %1
    
    # Populate fields
    - curl -X POST http://csse-s302g3.canterbury.ac.nz:8443/api/populate
    
  artifacts:
    paths:
      - backend/target/universal/*.zip
    expire_in: 1 week
  except:
    - tags

release-artifacts:
 stage: deploy
 script:
    - cd ./backend
    - sbt dist
    
    # Kill existing process (if any)
    - echo $PWD

    - kill $(cat target/universal/team300-travelea-1.0.0-SNAPSHOT/RUNNING_PID)
    
    # Deploy to server http://csse-s302g3.canterbury.ac.nz:8443/
    - cd target/universal
    - unzip team300-travelea-1.0.0-SNAPSHOT.zip
    - rm team300-travelea-1.0.0-SNAPSHOT.zip
    - cd team300-travelea-1.0.0-SNAPSHOT/bin
    - ./team300-travelea -Dplay.http.secret.key=QCYtAnfkaZiwrNwnxIlR6CTfG3gf90Latabg5241ABR5W1uDFNIk1 -Dplay.evolutions.db.default.autoApply=true -Dhttp.port=8443
    - disown -h %1
    
    # Populate fields
    - curl -X POST http://csse-s302g3.canterbury.ac.nz:8443/api/populate

 artifacts:
    paths:
    - backend/target/universal/*.zip
 only:
    - tags
    
update-sonar:
    stage: deploy
    script:
        - cd ./backend
        - sbt dist
        - ls -la
        - cd ../
        - echo $PWD
        - chmod -R 777 .
        - /opt/sonarqubeScanner/bin/sonar-scanner
    only:
        - master@seng302-2019/team-300
