# tag_checker:
#   stage: build
#   script:
#     - python tag_checker.py $CI_COMMIT_TAG
#   only:
#     - tags

# junit:
#   stage: test
#   script:
#     - sbt test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - /frontend/node_modules/

before_script:
  - cd ./frontend
  - npm install
  - cd ../

# Recent artifacts - all non-tagged branches
recent-artifacts:
  stage: deploy
  script:
    - sbt dist
    - rm -rf /srv/production/build/*
    - unzip target/universal/team300-travelea-1.0.0-SNAPSHOT.zip -d /srv/production/build/
  artifacts:
    paths:
      - target/universal/*.zip
    expire_in: 1 week
  only:
   - master@seng302-2019/team-300
  except:
    - tags

# Release artifacts - tagged branch
release-artifacts:
  stage: deploy
  script:
     - sbt dist
  artifacts:
     paths:
     - target/universal/*.zip
  only:
     - tags

# Deploy production server - tagged branch
deploy-production-server:
  stage: deploy
  script:
  - sudo rm -rf /srv/production/build/*
  - sudo unzip target/universal/team300-travelea-1.0.0-SNAPSHOT.zip -d /srv/production/build/
  only:
  - tags

# Deploy develop server - all non-tagged master commits
deploy-develop-server:
  stage: deploy
  script:
  - sudo rm -rf /srv/production/build/*
  - sudo unzip target/universal/team300-travelea-1.0.0-SNAPSHOT.zip -d /srv/production/build/
  only:
  - master@seng302-2019/team-300
  except:
  - tags
    
    
# # Run sonar scanner on master commits
# update-sonar:
#     stage: deploy
#     script:
#         - sbt dist
#         - chmod -R 777 .
#         - /opt/sonarqubeScanner/bin/sonar-scanner
#     only:
#         - master@seng302-2019/team-300
