tag_checker:
  stage: build
  script:
    - python tag_checker.py $CI_COMMIT_TAG
  only:
    - tags
    
release-artifacts-frontend:
  stage: deploy
  script:
    - cd ./frontend && npm install && npm run build 
  artifacts:
    paths:
      - frontend
