stages:
- test
- build
- deploy


# tag_checker:
#   stage: build
#   script:
#     - python tag_checker.py $CI_COMMIT_TAG
#   only:
#     - tags

# junit:
#   stage: test
#   script:
#     - sbt test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - ./frontend/node_modules/

before_script:
  - cd ./frontend
  - npm install
  - cd ../

# Recent artifacts - all non-tagged branches
recent-artifacts:
  stage: build
  script:
    - sbt dist
  artifacts:
    paths:
      - target/universal/*.zip
    expire_in: 1 week
  only:
   - master@seng302-2019/team-300
  except:
    - tags

# Release artifacts - tagged branch
release-artifacts:
  stage: build
  script:
     - sbt dist
  artifacts:
     paths:
     - target/universal/*.zip
  only:
     - tags

# Deploy production server - tagged branch
deploy-production-server:
  stage: deploy
  dependencies:
  - release-artifacts
  script:
  - sudo systemctl stop Production
  - sudo rm -rf /srv/production/build/*
  - sudo unzip target/universal/team300-travelea-1.0.0-SNAPSHOT.zip -d /srv/production/build/
  - sudo systemctl start Production
  environment:
    name: production
    url: https://csse-s302g3.canterbury.ac.nz/
  only:
  - tags

# Deploy develop server - all non-tagged master commits
deploy-develop-server:
  stage: deploy
  dependencies:
  - recent-artifacts
  script:
  - sudo systemctl stop Develop
  - sudo rm -rf /srv/develop/build/*
  - sudo unzip target/universal/team300-travelea-1.0.0-SNAPSHOT.zip -d /srv/develop/build/
  - sudo systemctl start Develop
  environment:
    name: production
    url: https://csse-s302g3.canterbury.ac.nz:8433
  only:
  - master@seng302-2019/team-300
  except:
  - tags
    
