tag_checker:
  stage: build
  script:
    - python tag_checker.py $CI_COMMIT_TAG
  only:
    - tags

recent-artifacts:
  stage: deploy
  script:
    - sbt dist
  artifacts:
    paths:
      - target/universal/*.zip
    expire_in: 1 week
  except:
    - tags

release-artifacts:
 stage: deploy
 script:
    - sbt dist
 artifacts:
    paths:
    - target/universal/*.zip
 only:
    - tags
