junit:
  stage: test
  script:
    - cd ./backend
    - sbt test

recent-artifacts:
  stage: deploy
  script:
    - cd ./backend
    - sbt dist
  artifacts:
    paths:
      - backend/target/universal/*.zip
    expire_in: 1 week
  except:
    - tags

release-artifacts:
 stage: deploy
 script:
    - cd ./backend
    - sbt dist
 artifacts:
    paths:
    - backend/target/universal/*.zip
 only:
    - tags


    
    

