recent-artifacts:
  stage: deploy
  script:
    - cd ./backend
    - sbt dist
    - cd target/universal
    - unzip *.zip
    - cd team300-travelea-1.0.0-SNAPSHOT/bin
    - bash team300-travelea -Dplay.http.secret.key=QCYtAnfkaZiwrNwnxIlR6CTfG3gf90Latabg5241ABR5W1uDFNIk1 -Dplay.evolutions.db.default.autoApply=true -Dhttp.port=8443

  artifacts:
    paths:
      - backend/target/universal/*.zip
    expire_in: 1 week
  except:
    - tags

release-artifacts:
 stage: deploy
 script:
    - cd ./backend
    - sbt dist
    - echo $PWD
    - ls -la
 artifacts:
    paths:
    - backend/target/universal/*.zip
 only:
    - tags
    
update-sonar:
    stage: deploy
    script:
        - cd ./backend
        - sbt dist
        - echo $PWD
        - ls -la
        - cd ../
        - echo $PWD
        - chmod -R 777 .
        - /opt/sonarqubeScanner/bin/sonar-scanner
    only:
        - master@seng302-2019/team-300
