

# Run sonar scanner on master commits
update-sonar:
    stage: deploy
    script:
        - sbt dist
        - chmod -R 777 .
        - /opt/sonarqubeScanner/bin/sonar-scanner
    only:
        - master@seng302-2019/team-300
        - HOTFIX-Refine-sonarqube-scanning-scope-for-new-directory-structure
