# tag_checker:
#   stage: build
#   script:
#     - python tag_checker.py $CI_COMMIT_TAG
#   only:
#     - tags

# junit:
#   stage: test
#   script:
#     - sbt test


# recent artifacts on all non-tagged commits on any branch
recent-artifacts:
  stage: deploy
  script:
    - sbt dist
  artifacts:
    paths:
      - target/universal/*.zip
    expire_in: 1 week
  except:
    - tags


# Deploy prod server and release artifacts on tagged master commits
# release-artifacts:
#  stage: deploy
#  script:
#     - sbt dist
#     - cd ./target/universal
#     - sudo rm -rf /home/gitlab-runner/prod/*
#     - sudo cp team300-travelea-1.0.0-SNAPSHOT.zip /home/gitlab-runner/prod/
#     - sudo unzip /home/gitlab-runner/prod/team300-travelea-1.0.0-SNAPSHOT.zip -d /home/gitlab-runner/prod/

#  artifacts:
#     paths:
#     - target/universal/*.zip
#  only:
#     - tags


# # Deploy dev server on non-tagged master commits
# deploy-dev:
#   stage: deploy
#   script:
#     - sbt dist
#     - sudo systemctl stop Dev.service
#     - cd ./target/universal
#     - sudo rm -rf /home/gitlab-runner/dev/*
#     - sudo cp team300-travelea-1.0.0-SNAPSHOT.zip /home/gitlab-runner/dev/
#     - sudo unzip /home/gitlab-runner/dev/team300-travelea-1.0.0-SNAPSHOT.zip -d /home/gitlab-runner/dev/
#     - sudo systemctl start Dev.service
#   only:
#     - master@seng302-2019/team-300
#   except:
#     - tags
    
    
# # Run sonar scanner on master commits
# update-sonar:
#     stage: deploy
#     script:
#         - sbt dist
#         - chmod -R 777 .
#         - /opt/sonarqubeScanner/bin/sonar-scanner
#     only:
#         - master@seng302-2019/team-300
