tag_checker:
  stage: build
  script:
    - python tag_checker.py $CI_COMMIT_TAG
  only:
    - tags

junit:
  stage: test
  script:
    - cd ./backend && sbt test

recent-artifacts-backend:
  stage: deploy
  script:
    - cd ./backend && sbt dist
  artifacts:
    paths:
      - target/universal/*.zip
    expire_in: 1 week
  except:
    - tags

release-artifacts-backend:
 stage: deploy
 script:
    - cd ./backend && sbt dist
 artifacts:
    paths:
    - target/universal/*.zip
 only:
    - tags

update-sonar:
    stage: deploy
    script:
        - sonar-scanner
    only:
        - vue-restructure@seng302-2019/team-300
